name: publish-docs

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  make_doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: make docs
      run: |
        mkdir -p doc/html
        echo "<html><body><h1>$GITHUB_SHA Documentation Demo</h1></body></html>" > doc/html/index.html
    - name: upload docs
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: doc/html

  download:
    runs-on: ubuntu-latest
    needs: make_doc
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          name: documentation

      - name: Publish docs
        run: |
          echo "Publishing docs"
          ls -l documentation
          # Stuff to push docs to a web server
          # maybe using rsync
          # rsync -avz documentation/doc/html/ user@server:/path/to/docs